### PR TITLE
Prepare Release 1.2.0

### PR DESCRIPTION
**Pull request by carlosalberto**
* Indicate if a `Span`'s parent or link is remote using 2 bit flag.
  [#484](https://github.com/open-telemetry/opentelemetry-proto/pull/484)
* Add metric.metadata for supporting additional metadata on metrics
  [#514](https://github.com/open-telemetry/opentelemetry-proto/pull/514)

@open-telemetry/opamp-spec-approvers please review

cc @bogdandrutu

### CODE REVIEW

**Comment by carlosalberto** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/3868 will be unblocked by this release.

**Review by jack-berg — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by tigrannajaryan — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Review by marcalff — CHANGES_REQUESTED** [review]
Please fix #540 before releasing

**Comment by arminru** [comment]
> Please fix #540 before releasing

#541 would fix this one.

**Review by marcalff — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]
It seems nothing is blocking this release anymore?

**Pull request merged**
