### PR TITLE
removed Node and ProcessIdentifier

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
@tigrannajaryan can you please post the `CONTRIBUTING.md` with info on how to regenerate Go classes

### CODE REVIEW

**Comment by Oberon00** [comment]
@SergeyKanzhelev @tigrannajaryan Does the generated code really have to be committed? (#79)

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev contribution guidelines: https://github.com/open-telemetry/opentelemetry-proto/pull/83

**Comment by tigrannajaryan** [comment]
I vaguely remember @bogdandrutu asking to keep these for reference. I may be wrong though.

Otherwise, LGTM.

**Comment by SergeyKanzhelev** [comment]
I think @bogdandrutu meant to remove it: https://github.com/open-telemetry/opentelemetry-proto/pull/62#discussion_r349718310

image

**Pull request merged**
