### PR TITLE
Fix consistency for timestamp vs time and use unix_nano

### PR DESCRIPTION
**Pull request by bogdandrutu**
This is a small breaking change, but not for the on-wire format so binaries build with an older version will be able to talk to the collector still. Only when updating the protos will cause breaking.

### CODE REVIEW

**Comment by Oberon00** [comment]
I liked _unixnano better.

**Comment by bogdandrutu** [comment]
@Oberon00  unixnano is not a word :( all the IDEs that I use complain about that.

**Comment by SergeyKanzhelev** [comment]
should we do it after tagging the beta (https://github.com/open-telemetry/opentelemetry-proto/issues/128) or after?

**Comment by bogdandrutu** [comment]
I will do it immediately after this. An official beta release

**Comment by SergeyKanzhelev** [comment]
@Oberon00 do you still have concerns? If not, let's wrap up the beta

**Comment by Oberon00** [comment]
I am a bit concerned about the renamings in tracing/ but I think I'm not particularly affected, so for me it's OK to tag a beta with these changes.

**Comment by SergeyKanzhelev** [comment]
thank you for confirming

**Pull request merged**
