### PR TITLE
Move codeowners in .github directory

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by yurishkuro** [comment]
Unless this is functionally necessary (which I don't think it is), I prefer these metadata files in the root where they are easier to find.

**Review by Oberon00 — APPROVED** [review]
I prefer these files in the .github repository where they don't clutter the root. Also I think they are easy enough to find if they are all in one place.
(Note: I'm only a traces approver, so disregard the green color of the checkmark)

**Review by arminru — APPROVED** [review]
I agree with @Oberon00 but don't have a strong opinion - either is fine with me.

**Comment by bogdandrutu** [comment]
@yurishkuro my argument is mostly consistency, we have this everywhere and users would know the file is there.

**Pull request merged**
