### PR TITLE
Declare metrics beta, we should try to not break the protocol from now on

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by MrAlias — COMMENTED** [review]
Should this go through a beta phase first?

**Comment by tigrannajaryan** [comment]
> Should this go through a beta phase first?

I think this is a good idea. Buys us a bit more time to finalize things.

**Comment by jmacd** [comment]
Two months have passed and I'm really going to resist any changes at this point.

**Review by jmacd — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@MrAlias @jmacd updated to go to beta initially

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
