### PR TITLE
Mark metrics protocol as stable for the 0.9 release.

### PR DESCRIPTION
**Pull request by jsuereth**
- Metrics datamodel SiG confirms no breaking changes will be made going forward.
- All release-blocking issues for the protocol definitions are resolved.

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]
Yay!

**Comment by jsuereth** [comment]
Note: wait on this before merging a sec, going to sync in Tigran's schema_url change

**Review by jmacd — APPROVED** [review]
I edited the Changelog so that the introduction of attributes / deprecation of labels appears in the v0.9 changelog. (Correct me if I misread this.)

**Comment by tigrannajaryan** [comment]
@jsuereth just to confirm: did we conclude performance testing and decided no changes needed?

**Comment by tigrannajaryan** [comment]
I see https://github.com/open-telemetry/opentelemetry-proto/issues/287 is still open. I would expect the issue to be closed if we are done. If we are not done then we are tying our hands very significantly by declaring the metrics stable.

**Comment by jsuereth** [comment]
@tigrannajaryan we decided for #287 that we can do Go-specific changes outside of the proto, and performance for what we have was acceptable.  I.e. it's not release blocking.

I left the bug open to denote the work needed in go, but we can close it.   We also plan to do follow on work for on-going performance benchmarks in this repository (I'm slowly gettinga  massive PR ready for that on this repo)

**Pull request merged**
