### PR TITLE
Stop checking-in generated Golang code

### LINKED ISSUE #79: Remove generated code from repository
The generated go code should not be checked in into the repository. See also https://github.com/open-telemetry/opentelemetry-proto/pull/77#issuecomment-559260610

Usually you should generate the files only during the build and maybe publish an artifact with them but never check them into source control (the same way you don't check in binary executables). I see #74 stated reasons to generate the code in this repository, and I think having the build files here is fine. But having the generated code here seems wrong.

### PR DESCRIPTION
**Pull request by jmacd**
I believe this will fix the build in all the open PRs.
I believe both the OTel-Go SDK and Collector have stopped using these generated files.

Resolves #79

### CODE REVIEW

**Comment by jmacd** [comment]
The OTel-Go fix: https://github.com/open-telemetry/opentelemetry-go/pull/942

**Comment by MrAlias** [comment]
Can we gate this on a release of the Go SIG library to ensure downstream has a versoned source for this code? I can get this release done this afternoon.

**Comment by jmacd** [comment]
@MrAlias Is there going to be a problem? I would have assumed the Go dependency was pinned to an older release that had the generated code.

**Comment by yurishkuro** [comment]
@MrAlias sorry, didn't notice your comment. Hope it's not a problem, can revert it is.

**Comment by MrAlias** [comment]
> @MrAlias Is there going to be a problem? I would have assumed the Go dependency was pinned to an older release that had the generated code.

I think the worry was [this](https://github.com/open-telemetry/opentelemetry-proto/issues/79#issuecomment-659643521), but I don't think it is critical. I'll just make sure to get the release out today.

**Comment by MrAlias** [comment]
> @MrAlias sorry, didn't notice your comment. Hope it's not a problem, can revert it is.

Should be okay, not worth a revert.

**Pull request merged**
