### PR TITLE
Declare OTLP/JSON Stable

### PR DESCRIPTION
**Pull request by tigrannajaryan**
See also https://github.com/open-telemetry/opentelemetry-specification/pull/2930

### CODE REVIEW

**Comment by carlosalberto** [comment]
@tigrannajaryan I take for granted #363 is not a _hard_ requirement for this?

**Review by carlosalberto — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by jack-berg — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
@tigrannajaryan this should wait first for the specification to be released per our guidance correct? Anything that is specified in the specification repo becomes the rule once it is released.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan this should wait first for the specification to be released per our guidance correct? Anything that is specified in the specification repo becomes the rule once it is released.

Once we are ready (both PRs have enough approvals) we can merge both PRs at the same time.

**Review by Aneurysm9 — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Depends on https://github.com/open-telemetry/opentelemetry-specification/issues/3040

**Comment by bogdandrutu** [comment]
After https://github.com/open-telemetry/opentelemetry-specification/pull/2930 is merged the "protocol" part of the protobufs is stable, but what about the helpers (flag values (or mask values, unclear though)) that are not defined by the protocol, are these stable? What does it mean for JSON encoding?

**Comment by tigrannajaryan** [comment]
> After [open-telemetry/opentelemetry-specification#2930](https://github.com/open-telemetry/opentelemetry-specification/pull/2930) is merged the "protocol" part of the protobufs is stable, but what about the helpers (flag values (or mask values, unclear though)) that are not defined by the protocol, are these stable? What does it mean for JSON encoding?

Helpers are not visible anywhere on the wire (we intentionally disallowed enum values as strings to make this enum names don't end on wire), so I think the fact that we have helpers or don't have helpers has no impact for JSON encoding. Do you see this differently?

**Comment by tigrannajaryan** [comment]
> > After [open-telemetry/opentelemetry-specification#2930](https://github.com/open-telemetry/opentelemetry-specification/pull/2930) is merged the "protocol" part of the protobufs is stable, but what about the helpers (flag values (or mask values, unclear though)) that are not defined by the protocol, are these stable? What does it mean for JSON encoding?
> 
> Helpers are not visible anywhere on the wire (we intentionally disallowed enum values as strings to make sure enum names don't end on wire), so I think the fact that we have helpers or don't have helpers has no impact for JSON encoding. Do you see this differently?

@bogdandrutu does this answer your question? Any other concerns or we can move forward with this?

**Review by bogdandrutu — APPROVED** [review]
> @bogdandrutu does this answer your question? Any other concerns or we can move forward with this?

@tigrannajaryan you are correct, my comment is important for 1.0 but not for JSON stability.

**Comment by tigrannajaryan** [comment]
This is ready to be merged after 1.18 spec release.

**Comment by carlosalberto** [comment]
Merging as 1.18.0 was released _and_ https://github.com/open-telemetry/opentelemetry-specification/pull/2930 was merged.

**Pull request merged**
