### PR TITLE
Declare logs Stable

### PR DESCRIPTION
**Pull request by tigrannajaryan**
The log data model is now declared Stable: https://github.com/open-telemetry/opentelemetry-specification/pull/2387

The OTLP proto in this repository now matches the log data model
in the specification.

This PR declares OTLP proto for logs Stable as well.

--

Please review the messages related to logs in this repository and make sure they match the log data model in the spec.
If you have any other concerns with regards to declaring the logs Stable please voice them.

### CODE REVIEW

**Comment by codeboten** [comment]
Will moving forward the stability of JSON support with logs being declared stable? https://github.com/open-telemetry/opentelemetry-proto/issues/230

**Comment by tigrannajaryan** [comment]
> Will moving forward the stability of JSON support be possible with logs being declared stable? #230

JSON for all signal types (not just logs) is explicitly [declared Alpha](https://github.com/open-telemetry/opentelemetry-proto#maturity-level) for now. Declaring OTLP Logs stable will not change that. We will work on stabilizing JSON separately.

**Comment by tigrannajaryan** [comment]
Here is the audit that shows all log data model fields are present in OTLP:

Data Model     |OTLP
---------------|--------------------------------------------
Timestamp      |LogRecord.time_unix_nano
ObservedTimestamp|LogRecord. observed_time_unix_nano
TraceId        |LogRecord.trace_id
SpanId         |LogRecord.span_id
TraceFlags     |LogRecord.flags & TRACE_FLAGS_MASK
SeverityText   |LogRecord.severity_text
SeverityNumber |LogRecord.severity_number
Body           |LogRecord.body
Resource       | ResourceLogs.resource
InstrumentationScope| ScopeLogs.scope
Attributes     |LogRecord.attributes

**Comment by tigrannajaryan** [comment]
I would like to wait for https://github.com/open-telemetry/opentelemetry-log-collection/pull/466 to be merged and then consumed as a dependency in the Collector before we declare logs stable (that log-collection library PR makes changes to Timestamp/ObservedTimestamp column as defined by logs data model). We do not expect any pushback or log data model stability as a result of log-collection library changes, but I still would like to move slowly to give enough time for any unknown issues to be discovered.

**Comment by djaglowski** [comment]
@tigrannajaryan, yes, I know a a couple minor changes that need to happen. I'll also do a final audit to make sure we haven't missed anything. Will let you know.

**Comment by djaglowski** [comment]
The [final issue that I am aware](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9369) of has been addressed as of this morning.

**Comment by tigrannajaryan** [comment]
I want to also finish the removal of LogRecord Name field from the Collector codebase. It is currently blocked on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9258

**Review by codeboten — COMMENTED** [review]
> There are known issues that block log proto stability declaration that I am aware of. I believe this is now ready to move forward.

@tigrannajaryan did you mean there are *no* known issues?

**Review by djaglowski — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
> > There are known issues that block log proto stability declaration that I am aware of. I believe this is now ready to move forward.
> 
> @tigrannajaryan did you mean there are _no_ known issues?

Yes, updated, it was a typo.

**Review by codeboten — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]
we should get couple more +1 from log SIG members

**Review by pmm-sumo — APPROVED** [review]

**Review by zenmoto — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Let's merge this after 0.17.0 is released.

**Comment by tigrannajaryan** [comment]
This looks good to go. Merging.

**Pull request merged**
