### PR TITLE
Rename Event.description to name to match spec.

### PR DESCRIPTION
**Pull request by Oberon00**
See https://github.com/open-telemetry/opentelemetry-specification/blob/f2af73c0fb71732bc08a77ae106e4ae14154ecaf/specification/api-tracing.md#add-events

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please re-generate go files. `make gen-go` will do it (and you may need to run one of `install-proto*` before that if this the first time).

**Comment by yurishkuro** [comment]
In Jaeger we have a CI step that fails the build if rerunning proto generation produces a different results from what's checked in.

**Comment by Oberon00** [comment]
@tigrannajaryan I don't have an environment ready where I want to run some global install script. If someone else could push the make gen-go changes, that would be nice. Otherwise it will take some time.

**Comment by tigrannajaryan** [comment]
@Oberon00 here https://github.com/open-telemetry/opentelemetry-proto/pull/101
Please close this one.

**Comment by Oberon00** [comment]
Closing in favor of #101

**Pull request closed without merging**
